pipeline:
  build:
    image: node:10
    commands:
      - npm install --prefer-offline
      - npm run lint
      - npm run test
      - npm run build
      - npm run storybook:build
    volumes:
      - /tmp/cache-npm:/root/.npm
  docker:
    when:
      branch: [master]
      event: [push]
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: rsschool/ui
    tags: latest
  deploy:
    when:
      branch: [master]
      event: [push]
    image: appleboy/drone-ssh
    host: 172.31.2.208
    secrets: [ ssh_key, ssh_username ]
    port: 22
    command_timeout: 120
    script:
      - sleep 10
      - docker pull rsschool/ui
      - docker-compose stop ui
      - docker-compose rm -f ui
      - docker-compose up -d ui
